export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';

export const START_SAVING = 'START_SAVING';
export const SAVING_DONE = 'SAVING_DONE';

export const ADD_ENVIRONMENT = 'ADD_ENVIRONMENT';
export const DELETE_ENVIRONMENT = 'DELETE_ENVIRONMENT';
export const UPDATE_ENVIRONMENT = 'UPDATE_ENVIRONMENT';

export const SHOW_IMPORT_DIALOG = 'SHOW_IMPORT_DIALOG';
export const HIDE_IMPORT_DIALOG = 'HIDE_IMPORT_DIALOG';
